"""
Company Intelligence Recipe Templates

Generates Grabber scraping jobs for company reconnaissance:
- GitHub org/repos
- Engineering blog posts
- Glassdoor reviews
- Product/about pages

Used by the job application pipeline to build dossiers before applying.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Any


@dataclass
class CompanyTarget:
    """A company to research."""
    name: str
    domain: str | None = None
    github_org: str | None = None
    blog_url: str | None = None
    glassdoor_slug: str | None = None
    extra_urls: list[str] = field(default_factory=list)

    @property
    def slug(self) -> str:
        return re.sub(r"[^a-z0-9]+", "-", self.name.lower()).strip("-")


# ---------------------------------------------------------------------------
# Schema definitions for each source type
# ---------------------------------------------------------------------------

GITHUB_REPOS_SCHEMA = {
    "repos": {
        "fields": ["name", "language", "stars", "forks", "last_updated", "description", "topics"],
        "type": "list",
    }
}

GITHUB_ORG_SCHEMA = {
    "org": {
        "fields": ["name", "description", "location", "website", "public_repos", "followers"],
        "type": "object",
    }
}

BLOG_SCHEMA = {
    "posts": {
        "fields": ["title", "date", "author", "summary", "url", "tags"],
        "type": "list",
    }
}

GLASSDOOR_SCHEMA = {
    "reviews": {
        "fields": ["rating", "title", "pros", "cons", "role", "date", "recommend"],
        "type": "list",
    },
    "company_overview": {
        "fields": ["overall_rating", "recommend_pct", "ceo_approval", "total_reviews"],
        "type": "object",
    },
}

TECH_STACK_SCHEMA = {
    "technologies": {
        "fields": ["name", "category", "evidence", "confidence"],
        "type": "list",
    }
}


# ---------------------------------------------------------------------------
# Job Discovery recipe (Indeed search → structured job list)
# ---------------------------------------------------------------------------

JOB_DISCOVERY_SCHEMA = {
    "jobs": {
        "fields": [
            "title", "company", "location", "salary_range",
            "posted_date", "url", "description_snippet", "is_remote",
        ],
        "type": "list",
    }
}


def job_discovery_urls(keywords: str, location: str, max_pages: int = 3) -> list[str]:
    """Generate Indeed search URLs for pagination."""
    base = f"https://www.indeed.com/jobs?q={keywords}&l={location}"
    urls = [base]
    for page in range(1, max_pages):
        urls.append(f"{base}&start={page * 10}")
    return urls


def build_job_discovery_payload(
    keywords: str,
    location: str,
    max_pages: int = 3,
) -> dict[str, Any]:
    """Build a Grabber job payload for Indeed job discovery."""
    return {
        "recipe_name": "job_discovery",
        "urls": job_discovery_urls(keywords, location, max_pages),
        "schema": JOB_DISCOVERY_SCHEMA,
        "metadata": {
            "keywords": keywords,
            "location": location,
            "source": "indeed",
        },
    }


# ---------------------------------------------------------------------------
# Company Intel recipe (multi-source company research)
# ---------------------------------------------------------------------------

def build_company_intel_urls(target: CompanyTarget) -> list[dict[str, Any]]:
    """
    Build URL list with per-URL field hints.

    Returns list of {url, source_type, field_hints} dicts.

    `field_hints` documents which fields we want from each source.
    They are NOT extraction selectors — actual extraction schemas are
    auto-generated by the Grabber SchemaGenerator (CSS/XPath/Extruct).
    Never inject field_hints into LLM prompts: keep schema declared in
    selectors, not in prompt text.
    """
    sources: list[dict[str, Any]] = []

    if target.github_org:
        org = target.github_org
        sources.append({
            "url": f"https://github.com/{org}",
            "source_type": "github_org",
            "field_hints": GITHUB_ORG_SCHEMA,
        })
        sources.append({
            "url": f"https://github.com/orgs/{org}/repositories?type=source&sort=updated",
            "source_type": "github_repos",
            "field_hints": GITHUB_REPOS_SCHEMA,
        })

    if target.blog_url:
        sources.append({
            "url": target.blog_url,
            "source_type": "blog",
            "field_hints": BLOG_SCHEMA,
        })

    if target.glassdoor_slug:
        sources.append({
            "url": f"https://www.glassdoor.com/Reviews/{target.glassdoor_slug}-Reviews",
            "source_type": "glassdoor",
            "field_hints": GLASSDOOR_SCHEMA,
        })

    # Company website pages
    if target.domain:
        for path in ["/about", "/careers", "/engineering", "/tech", "/stack"]:
            sources.append({
                "url": f"https://{target.domain}{path}",
                "source_type": "website",
                "field_hints": TECH_STACK_SCHEMA,
            })

    for url in target.extra_urls:
        sources.append({
            "url": url,
            "source_type": "extra",
            "field_hints": TECH_STACK_SCHEMA,
        })

    return sources


def build_company_intel_payload(target: CompanyTarget) -> dict[str, Any]:
    """
    Build a Grabber job payload for company intelligence gathering.

    Returns a payload dict with:
      - recipe_name: unique name for this company's intel run
      - sources: list of {url, source_type, field_hints} — field_hints document
        what fields we want, NOT extraction selectors (those are auto-generated
        by SchemaGenerator; field names must never appear in LLM prompts)
      - urls: flat list of all URLs to scrape (for worker dispatch)
      - metadata: company identifiers for project tracking

    NOTE: There is no top-level 'schema' key. Grabber workers use
    auto-generated extraction schemas (CSS/XPath) from SchemaGenerator,
    not field-name lists. A 'schema' key with a field-name dict would
    silently break ExtractHandler (schema.get("fields", []) returns []).
    """
    sources = build_company_intel_urls(target)
    return {
        "recipe_name": f"company_intel_{target.slug}",
        "sources": sources,
        "urls": [s["url"] for s in sources],
        "metadata": {
            "company_name": target.name,
            "domain": target.domain,
            "github_org": target.github_org,
        },
    }
